"""ConfigTableRealStats

Revision ID: f1092bf52761
Revises: 1b2059909caa
Create Date: 2024-09-06 15:59:29.212127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1092bf52761'
down_revision = '1b2059909caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_log_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('pulseOnLength',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('HarvardAparatus',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('Channel',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('cycleLength',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('plateName',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('stimFreq',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('timeSampling',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('stimulation_start',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('stimulation_end',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('pharmacological',
               existing_type=mysql.BIGINT(),
               type_=sa.Boolean(),
               nullable=False)
        batch_op.alter_column('voltage1',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('pulseDuration1',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('frequency1',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('current1',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('charge1',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('chargeDifference1',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('maturationPercentage1',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('energy1',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('rms1',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('voltage2',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('pulseDuration2',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('frequency2',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('current2',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('charge2',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('chargeDifference2',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('maturationPercentage2',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('energy2',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('rms2',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_log_data', schema=None) as batch_op:
        batch_op.alter_column('rms2',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('energy2',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('maturationPercentage2',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('chargeDifference2',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('charge2',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('current2',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('frequency2',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('pulseDuration2',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('voltage2',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('rms1',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('energy1',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('maturationPercentage1',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('chargeDifference1',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('charge1',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('current1',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('frequency1',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('pulseDuration1',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('voltage1',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('pharmacological',
               existing_type=sa.Boolean(),
               type_=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('stimulation_end',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('stimulation_start',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('timeSampling',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('stimFreq',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
        batch_op.alter_column('plateName',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('cycleLength',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('Channel',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('HarvardAparatus',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('pulseOnLength',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
